# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 427cf4059a6cf74c753cee07cf337d17ab942722d7fd821fd7250181e11534ded69383a3ac258f1badef40d192b0eecd09e5b1564e05d788e4d5a1266501a148

test:
  secret_key_base: ed4ad791367918f2f282e403212570d6133c9d178c9c43edae2b8d913223659bbfe417014afdd4fe483410555561abfc01324844162db12beb482ab424ec08cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
